config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'

  resources :projects do
    resources :members
  end
  resources :members do
    resources :projects
  end
  resources :teams do
    resources :members
  end

  get '/styles', to: 'application#styles'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sprint Members</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicon-32.png') %>
  </head>

  <body>
    <div id="header" class="row g-0 bg-light">
      <div class="col-12">
        <div class="logo">
          <h6>Welcome to the</h6>
          <h1>Member Admin Portal</h1>
        </div>
      </div>
    </div>
    <div class="row g-0 bg-info spacer">
    </div>
    <div id="main" class="row g-0">
      <div class="col-2 bg-dark">

        <div class="btn-group-vertical side-panel" role="group" aria-label="Vertical button group">
          <a href="<%= teams_path %>" class="btn btn-dark">TEAMS</a>
          <a href="<%= projects_path %>" class="btn btn-dark">PROJECTS</a>
          <a href="<%= members_path %>" class="btn btn-dark">MEMBERS</a>
        </div>

      </div>
      <div class="col page-container">
        <%= yield %>
      </div>
    </div>
    <div class="row g-0 bg-info spacer">
    </div>
    <div id="footer" class="row g-0 bg-info">
      <div class="col-12">
        <div id="footer-bar" class="row g-0">
          <div class="col col-2 text-start footer-name text-yellow">
            Bradley Carlson
          </div>
          <div class="col col-8 text-center d-flex justify-content-center align-items-center">
            <div><abbr title="Phone">P:</abbr>&nbsp; 303-906-7470</div>
            <div>&nbsp;&nbsp;|&nbsp;&nbsp;</div>
            <div><abbr title="Email">E:</abbr>&nbsp; <a href="mailto:bradleyrc@gmail.com">bradleyrc@gmail.com</a></div>
            <div>&nbsp;&nbsp;|&nbsp;&nbsp;</div>
            <div><i class="fa fa-linkedin"></i>&nbsp;<a href="https://www.linkedin.com/in/carlsonee/">carlsonee</a></div>
          </div>
          <div class="col col-2 text-end">
            &copy; 2022
          </div>
        </div>
      </div>
    </div>

    <div id="alerts">
    </div>

    <% if !Rails.env.production? && !Rails.env.staging? %>
      <script crossorigin src="https://unpkg.com/react@17/umd/react.development.js"></script>
      <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
    <% else %>
      <script crossorigin src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
      <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
    <% end %>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :jsfooter %>

    <% if flash[:success].present? %>
      <script>$(function() { SPRINT.showAlert("<%= flash[:success] %>", "success") });</script>
    <% end %>

    <% if flash[:error].present? %>
      <script>$(function() { SPRINT.showAlert("<%= flash[:error] %>", "danger") });</script>
    <% end %>

    <% if flash[:warning].present? %>
      <script>$(function() { SPRINT.showAlert("<%= flash[:warning] %>", "warning") });</script>
    <% end %>

  </body>
</html>